exports.FRIEND_STATUS = {
    "CREATED": "CREATED",
    "AWAITING": "AWAITING",
    "ACCEPTED": "ACCEPTED",
    "REFUSED": "REFUSED",
    "DELETED": "DELETED"
}

exports.SUB_FRIENDSHIP_TYPES = {
    "ACCEPTED" : "ACCEPTED",
    "RECEIVED": "RECEIVED",
}

exports.NOTIFICATION_TYPES = {
    "MESSAGE": "MESSAGE",
    "FRIENDSHIP": "FRIENDSHIP",
}

exports.REPORT_TYPES = {
    "SCAM": "SCAM",
    "CATFISH": "CATFISH",
    "HARASSMENT": "HARASSMENT",
    "UNAPROPRIAT_NAME": "UNAPROPRIAT_NAME",
    "THE_PICK": "THE_PICK",
    "OTHER": "OTHER",
}

exports.REPORT_STATUS = {
    "CREATED": "CREATED",
    "BANNED": "BANNED",
    "RESOLVED": "RESOLVED"
}
