exports.FRIEND_STATUS = {
    "CREATED": "CREATED",
    "AWAITING": "AWAITING",
    "ACCEPTED": "ACCEPTED",
    "REFUSED": "REFUSED",
    "DELETED": "DELETED"
}

exports.NOTIFICATION_TYPES = {
    "MESSAGE": "MESSAGE",
    "FRIENDSHIP": "FRIENDSHIP",
}